[project]
name = "examples"
version = "0.0.0"
description = "Example usages of Jitter"
requires-python = ">=3.12"
dependencies = [
    "jitter-llm",
]

[tool.uv.sources]
jitter-llm = { path = "..", editable = true }
